[package]
name = "async-sea-orm-session"
version = "0.1.0+dev0"
edition = "2021"

[package.metadata.docs.rs]
features = [
    "migration",
]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["migration"]
migration = ["sea-orm-migration"]

[dependencies]
async-session = { version = "3.0" }
sea-orm = { version = "0.8" }
sea-orm-migration = { version = "0.8", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0" }

[dev-dependencies]
tokio = { version = "1.19", features = ["rt", "macros"]}
sea-orm = { version = "0.8", features = ["runtime-tokio-rustls", "sqlx-sqlite"] }