[package]
name = "async-sea-orm-session"
version = "0.1.0+dev0"
edition = "2021"

[package.metadata.docs.rs]
features = [
    "sqlx-postgres",
    "sqlx-sqlite",
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "runtime-tokio-native-tls",
    "runtime-async-std-rustls",
    "runtime-async-std-native-tls",
    "migration",
]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["runtime-tokio-rustls", "migration"]
postgres = ["sea-orm/sqlx-postgres"]
sqlite = ["sea-orm/sqlx-sqlite"]
mysql = ["sea-orm/sqlx-mysql"]
runtime-async-std-native-tls = ["sea-orm/runtime-async-std-native-tls"]
runtime-async-std-rustls = ["sea-orm/runtime-async-std-rustls"]
runtime-tokio-native-tls = ["sea-orm/runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sea-orm/runtime-tokio-rustls"]
migration = ["sea-orm-migration"]

[dependencies]
async-session = { version = "3.0" }
sea-orm = { version = "0.8" }
sea-orm-migration = { version = "0.8", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0" }

[dev-dependencies]
tokio = { version = "1.19", features = ["rt", "macros"]}